version: 2.1
orbs:
  ci: bigcommerce/internal@volatile
  microapp: bigcommerce/internal-microapp@volatile

default_params: &default_params
  context: Bintray Access

workflows:
  version: 2
  ci-checks:
    jobs:
      - microapp/lint:
        <<: *default_params
      - microapp/test:
        <<: *default_params
      - microapp/build:
        <<: *default_params
      - ci/validate-commits

      - microapp/upload-artifact:
          context: Artifact Bucket Access
          requires:
            - microapp/lint
            - microapp/test
            - microapp/build

      - ci/notify-success:
          requires:
            - ci/validate-commits
            - microapp/upload-artifact
